# Generated by Django 6.0.2 on 2026-02-25 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='voyage',
            name='lieu_ramassage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='conducteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='date_arrivee',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='date_depart',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='prix_par_place',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
