# Generated by Django 6.0.2 on 2026-02-25 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0002_remove_voyage_created_at_voyage_lieu_ramassage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='correspondance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='demande',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ville',
        ),
        migrations.AddField(
            model_name='correspondance',
            name='score_match',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demande',
            name='passager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='lieu_ramassage',
            field=models.CharField(blank=True, help_text='Lieu exact du rendez-vous', max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='correspondance',
            name='date_correspondance',
        ),
        migrations.RemoveField(
            model_name='correspondance',
            name='paiement_effectue',
        ),
        migrations.RemoveField(
            model_name='correspondance',
            name='passager_embarque',
        ),
        migrations.RemoveField(
            model_name='correspondance',
            name='validated_at',
        ),
    ]
