# Generated by Django 6.0.2 on 2026-02-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0003_alter_correspondance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='modele_voiture',
            field=models.CharField(default='', help_text='Marque et modèle du véhicule (ex: Toyota Corolla)', max_length=100),
        ),
        migrations.AddField(
            model_name='voyage',
            name='plaque_immatriculation',
            field=models.CharField(default='', help_text="Plaque d'immatriculation du véhicule", max_length=20),
        ),
        migrations.AddField(
            model_name='voyage',
            name='type_bagage_accepte',
            field=models.CharField(choices=[('petit', 'Petit (sac à main, petit sac)'), ('moyen', 'Moyen (valise cabine)'), ('gros', 'Gros (valises, encombrants)'), ('tous', 'Tous types acceptés')], default='moyen', help_text='Type de bagage accepté dans le véhicule', max_length=10),
        ),
    ]
