# Generated by Django 6.0.2 on 2026-02-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0004_voyage_vehicule_bagage'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondance',
            name='refus_conducteur',
            field=models.BooleanField(default=False, help_text='Le conducteur a refusé ce match'),
        ),
        migrations.AddField(
            model_name='correspondance',
            name='refus_passager',
            field=models.BooleanField(default=False, help_text='Le passager a annulé son intérêt'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='est_termine',
            field=models.BooleanField(default=False, help_text='Coché quand le trajet est terminé (masqué des recherches)'),
        ),
    ]
