# Generated by Django 5.2.8 on 2026-03-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0006_avis_apres_trajet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_profil',
            field=models.ImageField(blank=True, help_text='Photo de profil (optionnelle)', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='photo_vehicule',
            field=models.ImageField(blank=True, help_text='Photo du véhicule (optionnelle)', null=True, upload_to='vehicles/'),
        ),
    ]
