# Generated by Django 6.0.2 on 2026-03-16 05:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0006_avis_apres_trajet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='car_photo',
            field=models.ImageField(blank=True, help_text='Photo of your vehicle for verification', null=True, upload_to='car_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='driver_license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='driver_license_photo',
            field=models.ImageField(blank=True, help_text="Photo of your driver's license", null=True, upload_to='driver_license_photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='driver_license_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_photo',
            field=models.ImageField(blank=True, help_text='Photo of your ID for verification', null=True, upload_to='id_photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_score',
            field=models.IntegerField(default=50, help_text='0-100 score based on verification and ratings'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes on verification'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('not_started', 'Not Verified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='voyage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='driver_confirmed_dropoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voyage',
            name='driver_confirmed_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voyage',
            name='end_latitude',
            field=models.FloatField(blank=True, help_text='Latitude at trip end', null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='end_longitude',
            field=models.FloatField(blank=True, help_text='Longitude at trip end', null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Both driver and passenger have confirmed pickup/dropoff'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='start_latitude',
            field=models.FloatField(blank=True, help_text='Latitude at trip start', null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='start_longitude',
            field=models.FloatField(blank=True, help_text='Longitude at trip start', null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='voyage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone OTP',
                'verbose_name_plural': 'Phone OTPs',
            },
        ),
        migrations.CreateModel(
            name='TripValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_confirmed_by_driver', models.BooleanField(default=False)),
                ('pickup_confirmed_by_passenger', models.BooleanField(default=False)),
                ('pickup_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('dropoff_confirmed_by_driver', models.BooleanField(default=False)),
                ('dropoff_confirmed_by_passenger', models.BooleanField(default=False)),
                ('dropoff_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('dropoff_latitude', models.FloatField(blank=True, null=True)),
                ('dropoff_longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voyage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='covoiturage.voyage')),
            ],
        ),
    ]
