# Generated by Django 6.0.2 on 2026-03-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0007_profile_car_photo_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
