# Generated by Django 6.0.2 on 2026-04-12 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covoiturage", "0010_add_message_and_sync_voyage_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("topup", "Rechargement (Monetbil)"),
                            ("commission", "Commission plateforme"),
                            ("refund", "Remboursement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, help_text="Monetbil ID", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("currency", models.CharField(default="XAF", max_length=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="covoiturage_corresp_f48a73_idx",
            old_name="covoiturage_m_corresp_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="covoiturage_user_id_61bcf8_idx",
            old_name="covoiturage_notification_user_is_read_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="covoiturage_user_id_9485bf_idx",
            old_name="covoiturage_notification_user_created_idx",
        ),
        migrations.AddField(
            model_name="transaction",
            name="related_voyage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="covoiturage.voyage",
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="covoiturage.wallet",
            ),
        ),
    ]
