# Generated by Django 6.0.2 on 2026-03-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0010_add_message_and_sync_voyage_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='covoiturage_corresp_f48a73_idx',
            old_name='covoiturage_m_corresp_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='covoiturage_user_id_61bcf8_idx',
            old_name='covoiturage_notification_user_is_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='covoiturage_user_id_9485bf_idx',
            old_name='covoiturage_notification_user_created_idx',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_money_number',
            field=models.CharField(blank=True, default='', help_text='Numéro Mobile Money (MTN, Orange, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('moov', 'Moov Money'), ('airtel', 'Airtel Money'), ('wave', 'Wave'), ('other', 'Autre')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='Numéro WhatsApp (si différent)', max_length=20),
        ),
        migrations.AddField(
            model_name='voyage',
            name='accept_cash',
            field=models.BooleanField(default=True, help_text='Accepte le paiement en espèces'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='accept_mobile_money',
            field=models.BooleanField(default=True, help_text='Accepte le paiement par Mobile Money'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='currency',
            field=models.CharField(choices=[('XAF', 'FCFA (Afrique Centrale)'), ('XOF', "FCFA (Afrique de l'Ouest)"), ('NGN', 'Naira (Nigeria)'), ('GHS', 'Cedi (Ghana)'), ('KES', 'Shilling (Kenya)'), ('ZAR', 'Rand (Afrique du Sud)'), ('MAD', 'Dirham (Maroc)')], default='XAF', max_length=3),
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['phone', '-created_at'], name='covoiturage_phone_8658fb_idx'),
        ),
    ]
