# Generated by Django 6.0.2 on 2026-05-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covoiturage", "0011_transaction_wallet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondance",
            name="escrow_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="correspondance",
            name="escrow_reference",
            field=models.CharField(
                blank=True,
                help_text="Référence du paiement Mobile Money",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="correspondance",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("none", "Aucun paiement"),
                    ("held", "Fonds bloqués (escrow)"),
                    ("released", "Versé au conducteur"),
                    ("refunded", "Remboursé au passager"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="demande",
            name="end_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demande",
            name="end_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demande",
            name="start_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demande",
            name="start_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
