# Generated by Django 6.0.2 on 2026-03-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0011_phoneotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', help_text="Nom du contact d'urgence", max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', help_text="Téléphone du contact d'urgence", max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Homme'), ('female', 'Femme'), ('other', 'Autre'), ('prefer_not', 'Préfère ne pas dire')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='voyage',
            name='women_only',
            field=models.BooleanField(default=False, help_text='Trajet réservé aux femmes'),
        ),
    ]
