# Generated by Django 6.0.2 on 2026-05-31 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("covoiturage", "0012_correspondance_escrow_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="emergency_contact_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Non précisé"),
                    ("male", "Homme"),
                    ("female", "Femme"),
                    ("other", "Autre"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="referral_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=12
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="voyage",
            name="women_only",
            field=models.BooleanField(
                default=False, help_text="Trajet réservé aux femmes"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("topup", "Rechargement (Monetbil)"),
                    ("commission", "Commission plateforme"),
                    ("refund", "Remboursement"),
                    ("referral", "Bonus de parrainage"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RecurringTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville_depart", models.CharField(max_length=100)),
                (
                    "lieu_ramassage",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("ville_arrivee", models.CharField(max_length=100)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ]
                    ),
                ),
                ("heure_depart", models.TimeField()),
                (
                    "duree_minutes",
                    models.PositiveIntegerField(
                        default=240, help_text="Durée estimée du trajet"
                    ),
                ),
                ("places_disponibles", models.PositiveIntegerField(default=1)),
                (
                    "prix_par_place",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "plaque_immatriculation",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "modele_voiture",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "type_bagage_accepte",
                    models.CharField(default="moyen", max_length=10),
                ),
                ("women_only", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conducteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RouteAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville_depart", models.CharField(max_length=100)),
                ("ville_arrivee", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["active", "ville_depart", "ville_arrivee"],
                        name="covoiturage_active_5c44f6_idx",
                    )
                ],
            },
        ),
    ]
