# Generated by Django 6.0.2 on 2026-03-23 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0012_profile_emergency_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Homme'), ('female', 'Femme')], default='', max_length=12),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('cash', 'Espèces')], default='mobile_money', max_length=15)),
                ('provider', models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('moov', 'Moov Money'), ('airtel', 'Airtel Money'), ('wave', 'Wave'), ('cash', 'Espèces')], default='', max_length=10)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=15)),
                ('transaction_ref', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correspondance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='covoiturage.correspondance')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payer', '-created_at'], name='covoiturage_payer_i_0e1d2b_idx'), models.Index(fields=['correspondance', 'status'], name='covoiturage_corresp_8382cc_idx')],
            },
        ),
    ]
